import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.accenture.com/de-de/careers/jobdetails?id=R00329883_de&src=LINKEDINJP');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'JETZT BEWERBEN. Ein neuer Tab' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('button', { name: 'Accept Cookies' }).click();
  await page1.getByRole('button', { name: 'Autofill with Resume' }).click();
  await page1.getByRole('button', { name: 'Sign in with Google' }).click();
  await page1.goto('https://accenture.wd103.myworkdayjobs.com/en-US/AccentureCareers/job/Hamburg/Agentic-AI-MarTech-Strategist--all-genders-_R00329883/apply/autofillWithResume');
  await page1.getByRole('button', { name: 'Sign in with Google' }).click();
  await page1.getByRole('textbox', { name: 'Email or phone' }).fill('evgeny@s4biz.io');
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByRole('textbox', { name: 'Enter your password' }).fill('w@m6(}--@~j)xDpj');
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.goto('https://accenture.wd103.myworkdayjobs.com/en-US/AccentureCareers/job/Hamburg/Agentic-AI-MarTech-Strategist--all-genders-_R00329883/apply/autofillWithResume');
  await page1.getByRole('button', { name: 'Select file' }).click();
  await page1.locator('input[type="file"]').setInputFiles('Evgeny Vainshtein - CV 2026.pdf');
  await page1.getByRole('button', { name: 'Continue' }).click();
  await page1.getByRole('textbox', { name: 'How Did You Hear About Us?' }).click();
  await page1.getByRole('textbox', { name: 'How Did You Hear About Us?' }).fill('linkedin');
  await page1.getByRole('textbox', { name: 'How Did You Hear About Us?' }).press('Enter');
  await page1.getByRole('radio', { name: 'No' }).check();
  await page1.getByRole('button', { name: 'Country/Territory Georgia' }).click();
  await page1.getByText('Germany').click();
  await page1.getByRole('textbox', { name: 'Address Line 1' }).click();
  await page1.getByRole('textbox', { name: 'Address Line 1' }).fill('Herman J Bach Weg ');
  await page1.getByRole('textbox', { name: 'Address Line 1' }).press('Tab');
  await page1.getByRole('textbox', { name: 'Address Line 2' }).fill('16');
  await page1.getByRole('textbox', { name: 'Postal Code' }).click();
  await page1.getByRole('textbox', { name: 'Postal Code' }).fill('61169');
  await page1.getByRole('textbox', { name: 'City' }).dblclick();
  await page1.getByRole('textbox', { name: 'City' }).fill('Friedberg');
  await page1.getByRole('button', { name: 'Land Select One' }).click();
  await page1.getByText('Hesse').click();
  await page1.getByRole('textbox', { name: 'Phone Number' }).click();
  await page1.getByRole('textbox', { name: 'Phone Number' }).click();
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).fill('+49 157 8551545');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).fill('+49 1578551545');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).fill('1578551545');
  await page1.getByRole('button', { name: 'Save and Continue' }).click();
  await page1.getByRole('button', { name: 'Error Phone Number' }).click();
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page1.getByRole('textbox', { name: 'Phone Number' }).fill('15785541545');
  await page1.getByRole('button', { name: 'Save and Continue' }).click();
  await page1.getByRole('button', { name: 'Save and Continue' }).click();
  await page1.getByLabel('Work Experience 2', { exact: true }).getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 2', { exact: true }).getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 2', { exact: true }).getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 2', { exact: true }).getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 2', { exact: true }).getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page1.getByRole('group', { name: 'Education 1' }).getByLabel('Degree Select One Required').click();
  await page1.getByText('Bachelor\'s Degree').click();
  await page1.getByRole('group', { name: 'Education 1' }).getByLabel('Overall Result (GPA)').click();
  await page1.getByRole('group', { name: 'Education 1' }).getByLabel('Overall Result (GPA)').fill('84');
  await page1.getByLabel('Education 2').getByRole('button', { name: 'Delete' }).click();
  await page1.getByRole('group', { name: 'Languages 1' }).getByLabel('I am fluent in this language.').check();
  await page1.getByRole('group', { name: 'Languages 1' }).getByLabel('Overall Select One Required').click();
  await page1.getByText('C2 - Mastery').click();
  await page1.getByRole('button', { name: 'Language German Required' }).click();
  await page1.locator('div').filter({ hasText: /^German$/ }).first().click();
  await page1.getByRole('group', { name: 'Languages 2' }).getByLabel('Overall Select One Required').click();
  await page1.getByText('C1 - Expert').click();
  await page1.getByRole('group', { name: 'Languages 3' }).getByLabel('I am fluent in this language.').check();
  await page1.getByRole('group', { name: 'Languages 3' }).getByLabel('Overall Select One Required').click();
  await page1.getByText('C2 - Mastery').nth(1).click();
  await page1.getByRole('group', { name: 'Languages 4' }).getByLabel('I am fluent in this language.').check();
  await page1.getByRole('button', { name: 'Overall Select One Required' }).click();
  await page1.getByText('C2 - Mastery').nth(2).click();
  await page1.getByRole('button', { name: 'Save and Continue' }).click();
  await page1.getByRole('group', { name: 'All individuals employed by' }).getByLabel('Select One Required').click();
  await page1.getByRole('option', { name: 'Yes' }).click();
  await page1.getByRole('group', { name: 'At your current employer, are' }).getByLabel('Select One Required').click();
  await page1.getByText('No', { exact: true }).click();
  await page1.getByRole('button', { name: 'Select One Required' }).click();
  await page1.getByRole('listbox').getByText('Yes').click();
  await page1.getByRole('button', { name: 'Save and Continue' }).click();
  await page1.getByRole('button', { name: 'What is your legal gender?' }).click();
  await page1.getByText('Male', { exact: true }).click();
  await page1.getByRole('button', { name: 'Please Select Your Pronoun' }).click();
  await page1.getByRole('option', { name: 'He/Him' }).click();
  await page1.getByRole('button', { name: 'Save and Continue' }).click();
  await page1.getByRole('checkbox', { name: 'I accept.' }).check();
  await page1.getByRole('button', { name: 'Save and Continue' }).click();
  await page1.getByRole('button', { name: 'Submit' }).click();
});