import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://www.accenture.com/de-de/careers/jobdetails?id=R00329883_de&src=LINKEDINJP")
    with page.expect_popup() as page1_info:
        page.get_by_role("link", name="JETZT BEWERBEN. Ein neuer Tab").click()
    page1 = page1_info.value
    page1.get_by_role("button", name="Accept Cookies").click()
    page1.get_by_role("button", name="Autofill with Resume").click()
    page1.get_by_role("button", name="Sign in with Google").click()
    page1.goto("https://accenture.wd103.myworkdayjobs.com/en-US/AccentureCareers/job/Hamburg/Agentic-AI-MarTech-Strategist--all-genders-_R00329883/apply/autofillWithResume")
    page1.get_by_role("button", name="Sign in with Google").click()
    page1.get_by_role("textbox", name="Email or phone").fill("evgeny@s4biz.io")
    page1.get_by_role("button", name="Next").click()
    page1.get_by_role("textbox", name="Enter your password").fill("w@m6(}--@~j)xDpj")
    page1.get_by_role("button", name="Next").click()
    page1.goto("https://accenture.wd103.myworkdayjobs.com/en-US/AccentureCareers/job/Hamburg/Agentic-AI-MarTech-Strategist--all-genders-_R00329883/apply/autofillWithResume")
    page1.get_by_role("button", name="Select file").click()
    page1.locator("input[type=\"file\"]").set_input_files("Evgeny Vainshtein - CV 2026.pdf")
    page1.get_by_role("button", name="Continue").click()
    page1.get_by_role("textbox", name="How Did You Hear About Us?").click()
    page1.get_by_role("textbox", name="How Did You Hear About Us?").fill("linkedin")
    page1.get_by_role("textbox", name="How Did You Hear About Us?").press("Enter")
    page1.get_by_role("radio", name="No").check()
    page1.get_by_role("button", name="Country/Territory Georgia").click()
    page1.get_by_text("Germany").click()
    page1.get_by_role("textbox", name="Address Line 1").click()
    page1.get_by_role("textbox", name="Address Line 1").fill("Herman J Bach Weg ")
    page1.get_by_role("textbox", name="Address Line 1").press("Tab")
    page1.get_by_role("textbox", name="Address Line 2").fill("16")
    page1.get_by_role("textbox", name="Postal Code").click()
    page1.get_by_role("textbox", name="Postal Code").fill("61169")
    page1.get_by_role("textbox", name="City").dblclick()
    page1.get_by_role("textbox", name="City").fill("Friedberg")
    page1.get_by_role("button", name="Land Select One").click()
    page1.get_by_text("Hesse").click()
    page1.get_by_role("textbox", name="Phone Number").click()
    page1.get_by_role("textbox", name="Phone Number").click()
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").fill("+49 157 8551545")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").fill("+49 1578551545")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").fill("1578551545")
    page1.get_by_role("button", name="Save and Continue").click()
    page1.get_by_role("button", name="Error Phone Number").click()
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page1.get_by_role("textbox", name="Phone Number").fill("15785541545")
    page1.get_by_role("button", name="Save and Continue").click()
    page1.get_by_role("button", name="Save and Continue").click()
    page1.get_by_label("Work Experience 2", exact=True).get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 2", exact=True).get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 2", exact=True).get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 2", exact=True).get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 2", exact=True).get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page1.get_by_role("group", name="Education 1").get_by_label("Degree Select One Required").click()
    page1.get_by_text("Bachelor's Degree").click()
    page1.get_by_role("group", name="Education 1").get_by_label("Overall Result (GPA)").click()
    page1.get_by_role("group", name="Education 1").get_by_label("Overall Result (GPA)").fill("84")
    page1.get_by_label("Education 2").get_by_role("button", name="Delete").click()
    page1.get_by_role("group", name="Languages 1").get_by_label("I am fluent in this language.").check()
    page1.get_by_role("group", name="Languages 1").get_by_label("Overall Select One Required").click()
    page1.get_by_text("C2 - Mastery").click()
    page1.get_by_role("button", name="Language German Required").click()
    page1.locator("div").filter(has_text=re.compile(r"^German$")).first.click()
    page1.get_by_role("group", name="Languages 2").get_by_label("Overall Select One Required").click()
    page1.get_by_text("C1 - Expert").click()
    page1.get_by_role("group", name="Languages 3").get_by_label("I am fluent in this language.").check()
    page1.get_by_role("group", name="Languages 3").get_by_label("Overall Select One Required").click()
    page1.get_by_text("C2 - Mastery").nth(1).click()
    page1.get_by_role("group", name="Languages 4").get_by_label("I am fluent in this language.").check()
    page1.get_by_role("button", name="Overall Select One Required").click()
    page1.get_by_text("C2 - Mastery").nth(2).click()
    page1.get_by_role("button", name="Save and Continue").click()
    page1.get_by_role("group", name="All individuals employed by").get_by_label("Select One Required").click()
    page1.get_by_role("option", name="Yes").click()
    page1.get_by_role("group", name="At your current employer, are").get_by_label("Select One Required").click()
    page1.get_by_text("No", exact=True).click()
    page1.get_by_role("button", name="Select One Required").click()
    page1.get_by_role("listbox").get_by_text("Yes").click()
    page1.get_by_role("button", name="Save and Continue").click()
    page1.get_by_role("button", name="What is your legal gender?").click()
    page1.get_by_text("Male", exact=True).click()
    page1.get_by_role("button", name="Please Select Your Pronoun").click()
    page1.get_by_role("option", name="He/Him").click()
    page1.get_by_role("button", name="Save and Continue").click()
    page1.get_by_role("checkbox", name="I accept.").check()
    page1.get_by_role("button", name="Save and Continue").click()
    page1.get_by_role("button", name="Submit").click()
