import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://job-boards.eu.greenhouse.io/alpega/jobs/4948747101?gh_src=t0kkp112teu');
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('textbox', { name: 'First Name', exact: true }).dblclick();
  await page.getByRole('textbox', { name: 'First Name', exact: true }).fill('Evgeny');
  await page.getByRole('textbox', { name: 'First Name', exact: true }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Vainshtein');
  await page.getByRole('textbox', { name: 'Last Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Preferred First Name' }).fill('Jev');
  await page.getByRole('textbox', { name: 'Preferred First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).fill('evgeny@s4biz.io');
  await page.locator('.select__input-container').first().click();
  await page.getByRole('combobox', { name: 'Country' }).fill('ger');
  await page.getByRole('option', { name: 'Germany +' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('15785541545');
  await page.getByText('Location (City)*').click();
  await page.getByRole('combobox', { name: 'Location (City)' }).fill('Friedberg');
  await page.getByRole('option', { name: 'Friedberg, Hesse, Germany' }).click();
  await page.getByLabel('Resume/CV*').locator('button').filter({ hasText: 'Attach' }).click();
  await page.getByRole('group', { name: 'Resume/CV*' }).getByLabel('Attach').setInputFiles('Evgeny Vainshtein - CV 2026.pdf');
  await page.locator('button').filter({ hasText: 'Attach' }).click();
  await page.getByLabel('Attach').setInputFiles('Evgeny Vainshtein - Cover Letter 2026.pdf');
  await page.getByRole('textbox', { name: 'LinkedIn Profile' }).click();
  await page.getByRole('textbox', { name: 'LinkedIn Profile' }).fill('https://www.linkedin.com/in/feranicus/');
  await page.getByRole('textbox', { name: 'Website' }).click();
  await page.getByRole('textbox', { name: 'Website' }).fill('www.itzen.ai');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).click();
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).fill('I\'m currently Director of 4 SME consulting business units: Stars4business OU, S4biz UG, S4biz LDA & Cybergod LLC.\nThis is perfectly alligned with my current career path, experience and the knowlege that I can bring to your company');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).click();
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).click({
    button: 'right'
  });
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).click();
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).click();
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).click();
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).fill('I\'m currently Director of 4 SME consulting business units: Stars4business OU, S4biz UG, S4biz LDA & Cybergod LLC.\nThis is perfectly aligned with my current career path, experience and the knowlege that I can bring to your company');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'How does this job aligns with' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Have you led an engineering' }).click();
  await page.getByRole('textbox', { name: 'Have you led an engineering' }).fill('Yes multiple times even post M&A from 3 companies into one, plus very large applications and IT transformations to the cloud for Telefonica Germany and for LuxAir. Programs over 200ML Euro');
  await page.getByRole('textbox', { name: 'What is the largest' }).click();
  await page.getByRole('textbox', { name: 'What is the largest' }).fill('Currently I\'m directing managing 70 stakeholders where on every pizza there is a team leader.\nLargest was around 200 with same pizza structure ');
  await page.getByRole('textbox', { name: 'This role requires frequent' }).click();
  await page.getByRole('textbox', { name: 'This role requires frequent' }).fill('Currently I\'m single so I can travel over 60%');
  await page.getByRole('textbox', { name: 'What is your available start' }).click();
  await page.getByRole('textbox', { name: 'What is your available start' }).fill('I have one month notice period ');
  await page.getByRole('textbox', { name: 'What are your salary' }).click();
  await page.getByRole('textbox', { name: 'What are your salary' }).fill('My current salary is 120k base + 80K bonus');
  await page.getByRole('checkbox', { name: 'By checking this box, I agree' }).check();
  await page.getByRole('button', { name: 'Submit application' }).click();
});