import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://job-boards.eu.greenhouse.io/alpega/jobs/4948747101?gh_src=t0kkp112teu")
    page.get_by_role("button", name="Apply").click()
    page.get_by_role("textbox", name="First Name", exact=True).dblclick()
    page.get_by_role("textbox", name="First Name", exact=True).fill("Evgeny")
    page.get_by_role("textbox", name="First Name", exact=True).press("Tab")
    page.get_by_role("textbox", name="Last Name").fill("Vainshtein")
    page.get_by_role("textbox", name="Last Name").press("Tab")
    page.get_by_role("textbox", name="Preferred First Name").fill("Jev")
    page.get_by_role("textbox", name="Preferred First Name").press("Tab")
    page.get_by_role("textbox", name="Email").fill("evgeny@s4biz.io")
    page.locator(".select__input-container").first.click()
    page.get_by_role("combobox", name="Country").fill("ger")
    page.get_by_role("option", name="Germany +").click()
    page.get_by_role("textbox", name="Phone").fill("15785541545")
    page.get_by_text("Location (City)*").click()
    page.get_by_role("combobox", name="Location (City)").fill("Friedberg")
    page.get_by_role("option", name="Friedberg, Hesse, Germany").click()
    page.get_by_label("Resume/CV*").locator("button").filter(has_text="Attach").click()
    page.get_by_role("group", name="Resume/CV*").get_by_label("Attach").set_input_files("Evgeny Vainshtein - CV 2026.pdf")
    page.locator("button").filter(has_text="Attach").click()
    page.get_by_label("Attach").set_input_files("Evgeny Vainshtein - Cover Letter 2026.pdf")
    page.get_by_role("textbox", name="LinkedIn Profile").click()
    page.get_by_role("textbox", name="LinkedIn Profile").fill("https://www.linkedin.com/in/feranicus/")
    page.get_by_role("textbox", name="Website").click()
    page.get_by_role("textbox", name="Website").fill("www.itzen.ai")
    page.get_by_role("textbox", name="How does this job aligns with").click()
    page.get_by_role("textbox", name="How does this job aligns with").fill("I'm currently Director of 4 SME consulting business units: Stars4business OU, S4biz UG, S4biz LDA & Cybergod LLC.\nThis is perfectly alligned with my current career path, experience and the knowlege that I can bring to your company")
    page.get_by_role("textbox", name="How does this job aligns with").click()
    page.get_by_role("textbox", name="How does this job aligns with").click(button="right")
    page.get_by_role("textbox", name="How does this job aligns with").click()
    page.get_by_role("textbox", name="How does this job aligns with").click()
    page.get_by_role("textbox", name="How does this job aligns with").click()
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowUp")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").fill("I'm currently Director of 4 SME consulting business units: Stars4business OU, S4biz UG, S4biz LDA & Cybergod LLC.\nThis is perfectly aligned with my current career path, experience and the knowlege that I can bring to your company")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="How does this job aligns with").press("ArrowRight")
    page.get_by_role("textbox", name="Have you led an engineering").click()
    page.get_by_role("textbox", name="Have you led an engineering").fill("Yes multiple times even post M&A from 3 companies into one, plus very large applications and IT transformations to the cloud for Telefonica Germany and for LuxAir. Programs over 200ML Euro")
    page.get_by_role("textbox", name="What is the largest").click()
    page.get_by_role("textbox", name="What is the largest").fill("Currently I'm directing managing 70 stakeholders where on every pizza there is a team leader.\nLargest was around 200 with same pizza structure ")
    page.get_by_role("textbox", name="This role requires frequent").click()
    page.get_by_role("textbox", name="This role requires frequent").fill("Currently I'm single so I can travel over 60%")
    page.get_by_role("textbox", name="What is your available start").click()
    page.get_by_role("textbox", name="What is your available start").fill("I have one month notice period ")
    page.get_by_role("textbox", name="What are your salary").click()
    page.get_by_role("textbox", name="What are your salary").fill("My current salary is 120k base + 80K bonus")
    page.get_by_role("checkbox", name="By checking this box, I agree").check()
    page.get_by_role("button", name="Submit application").click()
