import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://kyndryl.wd5.myworkdayjobs.com/KyndrylProfessionalCareers/job/MesseTurm-DEFAMESS-HQ/Associate-Director---Customer-Technical-Solutioner-Cloud_R-64223-1');
  await page.getByRole('button', { name: 'Accept Cookies' }).click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: 'Autofill with Resume' }).click();
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Create Account' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('evgeny@s4biz.io');
  await page.getByRole('textbox', { name: 'Email Address' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('Ang0la1234!');
  await page.getByRole('textbox', { name: 'Password', exact: true }).press('Tab');
  await page.getByRole('textbox', { name: 'Verify New Password' }).fill('Ang0la1234!');
  await page.getByRole('checkbox', { name: 'Yes, I have read and consent' }).check();
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.goto('https://kyndryl.wd5.myworkdayjobs.com/en-US/KyndrylProfessionalCareers/login?redirect=%2Fen-US%2FKyndrylProfessionalCareers%2Fjob%2FMesseTurm-(DEFAMESS)-HQ%2FAssociate-Director---Customer-Technical-Solutioner-Cloud_R-64223-1%2Fapply%2FautofillWithResume');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('evgeny@s4biz.io');
  await page.getByRole('textbox', { name: 'Email Address' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Ang0la1234!');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Password' }).dblclick();
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('evgeny@s4biz.io');
  await page.getByRole('textbox', { name: 'Email Address' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('Ang0la1234!');
  await page.getByRole('textbox', { name: 'Password', exact: true }).press('Tab');
  await page.getByRole('textbox', { name: 'Verify New Password' }).fill('Ang0la1234!');
  await page.getByRole('checkbox', { name: 'Yes, I have read and consent' }).check();
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('evgeny@s4biz.io');
  await page.getByRole('textbox', { name: 'Email Address' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Ang0la1234!');
  await page.getByLabel('Sign In').click();
  await page.getByRole('banner').getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Forgot your password?' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('evgeny@s4biz.io');
  await page.getByRole('button', { name: 'Reset Password' }).click();
  await page.getByRole('banner').getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('evgeny@s4biz.io');
  await page.getByRole('textbox', { name: 'Email Address' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Ang0la1234!');
  await page.getByLabel('Forgot Password').getByRole('button', { name: 'Sign In' }).click();
  await page.goto('https://kyndryl.wd5.myworkdayjobs.com/KyndrylProfessionalCareers/job/MesseTurm-DEFAMESS-HQ/Associate-Director---Customer-Technical-Solutioner-Cloud_R-64223-1');
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: 'Autofill with Resume' }).click();
  await page.getByRole('button', { name: 'Select file' }).click();
  await page.locator('input[type="file"]').setInputFiles('Evgeny Vainshtein - CV 2026.pdf');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'How Did You Hear About Us?' }).click();
  await page.getByRole('textbox', { name: 'How Did You Hear About Us?' }).fill('link');
  await page.getByRole('textbox', { name: 'How Did You Hear About Us?' }).press('Enter');
  await page.getByText('LinkedIn', { exact: true }).click();
  await page.getByRole('radio', { name: 'No' }).check();
  await page.getByRole('button', { name: 'Country Georgia Required' }).click();
  await page.getByText('Germany').click();
  await page.getByRole('textbox', { name: 'Street' }).dblclick();
  await page.getByRole('textbox', { name: 'Street' }).fill('Herman J Bach Weg 16');
  await page.getByRole('textbox', { name: 'Postal Code' }).click();
  await page.getByRole('textbox', { name: 'Postal Code' }).fill('61169');
  await page.getByRole('textbox', { name: 'Postal Code' }).press('Tab');
  await page.getByRole('textbox', { name: 'City' }).fill('Friedberg ');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Error Additional Address' }).click();
  await page.getByRole('textbox', { name: 'Street' }).click();
  await page.getByRole('textbox', { name: 'Street' }).fill('Herman J Bach Weg ');
  await page.getByRole('textbox', { name: 'Street' }).press('Tab');
  await page.getByRole('textbox', { name: 'Additional Address' }).fill('16');
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Error Phone Device Type' }).click();
  await page.getByRole('button', { name: 'Phone Device Type Select One' }).click();
  await page.getByText('Mobile').click();
  await page.getByRole('group', { name: 'Phone' }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Error Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('157 855 1545');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('157855 1545');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Phone Number' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('1578551545');
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('group', { name: 'Work Experience 1', exact: true }).getByLabel('Job Title*').dblclick();
  await page.getByRole('group', { name: 'Work Experience 1', exact: true }).getByLabel('Job Title*').click();
  await page.getByRole('group', { name: 'Work Experience 1', exact: true }).getByLabel('Job Title*').dblclick();
  await page.getByRole('group', { name: 'Work Experience 1', exact: true }).getByLabel('Location*').click();
  await page.getByRole('group', { name: 'Work Experience 1', exact: true }).getByLabel('Job Title*').fill('Principal Technical G& Presales');
  await page.getByRole('group', { name: 'Work Experience 1', exact: true }).getByLabel('Location*').fill('Germany');
  await page.getByLabel('Work Experience 2', { exact: true }).getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 2', { exact: true }).getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 2', { exact: true }).getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 2', { exact: true }).getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 2', { exact: true }).getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('group', { name: 'Work Experience 4' }).getByLabel('Location*').click();
  await page.getByRole('group', { name: 'Work Experience 4' }).getByLabel('Location*').fill('Germany');
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByLabel('Work Experience 6').getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('group', { name: 'Education 1' }).getByLabel('Degree Select One Required').click();
  await page.getByText('Bachelors').click();
  await page.getByRole('group', { name: 'Education 1' }).getByLabel('Overall Result (GPA)').click();
  await page.getByRole('group', { name: 'Education 1' }).getByLabel('Overall Result (GPA)').fill('84');
  await page.locator('div:nth-child(3) > div:nth-child(4) > .css-bh8c3f > .css-zfgw5f').click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('group', { name: 'Are you eligible/legally' }).getByLabel('Select One Required').click();
  await page.getByText('Yes').click();
  await page.getByRole('button', { name: 'Select One', exact: true }).click();
  await page.getByText('No', { exact: true }).click();
  await page.getByRole('button', { name: 'Select One Required' }).click();
  await page.getByRole('listbox').getByText('No').click();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('checkbox', { name: 'I consent to the Kyndryl' }).check();
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Return to Home' }).click();
});