import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://kyndryl.wd5.myworkdayjobs.com/KyndrylProfessionalCareers/job/MesseTurm-DEFAMESS-HQ/Associate-Director---Customer-Technical-Solutioner-Cloud_R-64223-1")
    page.get_by_role("button", name="Accept Cookies").click()
    page.get_by_role("button", name="Apply").click()
    page.get_by_role("button", name="Autofill with Resume").click()
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("heading", name="Create Account").press("ArrowDown")
    page.get_by_role("textbox", name="Email Address").click()
    page.get_by_role("textbox", name="Email Address").fill("evgeny@s4biz.io")
    page.get_by_role("textbox", name="Email Address").press("Tab")
    page.get_by_role("textbox", name="Password", exact=True).fill("Ang0la1234!")
    page.get_by_role("textbox", name="Password", exact=True).press("Tab")
    page.get_by_role("textbox", name="Verify New Password").fill("Ang0la1234!")
    page.get_by_role("checkbox", name="Yes, I have read and consent").check()
    page.get_by_role("button", name="Create Account").click()
    page.goto("https://kyndryl.wd5.myworkdayjobs.com/en-US/KyndrylProfessionalCareers/login?redirect=%2Fen-US%2FKyndrylProfessionalCareers%2Fjob%2FMesseTurm-(DEFAMESS)-HQ%2FAssociate-Director---Customer-Technical-Solutioner-Cloud_R-64223-1%2Fapply%2FautofillWithResume")
    page.get_by_role("textbox", name="Email Address").click()
    page.get_by_role("textbox", name="Email Address").fill("evgeny@s4biz.io")
    page.get_by_role("textbox", name="Email Address").press("Tab")
    page.get_by_role("textbox", name="Password").fill("Ang0la1234!")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("textbox", name="Password").dblclick()
    page.get_by_role("button", name="Create Account").click()
    page.get_by_role("textbox", name="Email Address").click()
    page.get_by_role("textbox", name="Email Address").fill("evgeny@s4biz.io")
    page.get_by_role("textbox", name="Email Address").press("Tab")
    page.get_by_role("textbox", name="Password", exact=True).fill("Ang0la1234!")
    page.get_by_role("textbox", name="Password", exact=True).press("Tab")
    page.get_by_role("textbox", name="Verify New Password").fill("Ang0la1234!")
    page.get_by_role("checkbox", name="Yes, I have read and consent").check()
    page.get_by_role("button", name="Create Account").click()
    page.get_by_role("textbox", name="Email Address").click()
    page.get_by_role("textbox", name="Email Address").fill("evgeny@s4biz.io")
    page.get_by_role("textbox", name="Email Address").press("Tab")
    page.get_by_role("textbox", name="Password").fill("Ang0la1234!")
    page.get_by_label("Sign In").click()
    page.get_by_role("banner").get_by_role("button", name="Sign In").click()
    page.get_by_role("button", name="Close").click()
    page.get_by_role("button", name="Forgot your password?").click()
    page.get_by_role("textbox", name="Email Address").click()
    page.get_by_role("textbox", name="Email Address").fill("evgeny@s4biz.io")
    page.get_by_role("button", name="Reset Password").click()
    page.get_by_role("banner").get_by_role("button", name="Sign In").click()
    page.get_by_role("textbox", name="Email Address").click()
    page.get_by_role("textbox", name="Email Address").fill("evgeny@s4biz.io")
    page.get_by_role("textbox", name="Email Address").press("Tab")
    page.get_by_role("textbox", name="Password").fill("Ang0la1234!")
    page.get_by_label("Forgot Password").get_by_role("button", name="Sign In").click()
    page.goto("https://kyndryl.wd5.myworkdayjobs.com/KyndrylProfessionalCareers/job/MesseTurm-DEFAMESS-HQ/Associate-Director---Customer-Technical-Solutioner-Cloud_R-64223-1")
    page.get_by_role("button", name="Apply").click()
    page.get_by_role("button", name="Autofill with Resume").click()
    page.get_by_role("button", name="Select file").click()
    page.locator("input[type=\"file\"]").set_input_files("Evgeny Vainshtein - CV 2026.pdf")
    page.get_by_role("button", name="Continue").click()
    page.get_by_role("textbox", name="How Did You Hear About Us?").click()
    page.get_by_role("textbox", name="How Did You Hear About Us?").fill("link")
    page.get_by_role("textbox", name="How Did You Hear About Us?").press("Enter")
    page.get_by_text("LinkedIn", exact=True).click()
    page.get_by_role("radio", name="No").check()
    page.get_by_role("button", name="Country Georgia Required").click()
    page.get_by_text("Germany").click()
    page.get_by_role("textbox", name="Street").dblclick()
    page.get_by_role("textbox", name="Street").fill("Herman J Bach Weg 16")
    page.get_by_role("textbox", name="Postal Code").click()
    page.get_by_role("textbox", name="Postal Code").fill("61169")
    page.get_by_role("textbox", name="Postal Code").press("Tab")
    page.get_by_role("textbox", name="City").fill("Friedberg ")
    page.get_by_role("textbox", name="Phone Number").click()
    page.get_by_role("textbox", name="Phone Number").click()
    page.get_by_role("textbox", name="Phone Number").click()
    page.get_by_role("button", name="Save and Continue").click()
    page.get_by_role("button", name="Error Additional Address").click()
    page.get_by_role("textbox", name="Street").click()
    page.get_by_role("textbox", name="Street").fill("Herman J Bach Weg ")
    page.get_by_role("textbox", name="Street").press("Tab")
    page.get_by_role("textbox", name="Additional Address").fill("16")
    page.get_by_role("button", name="Save and Continue").click()
    page.get_by_role("button", name="Error Phone Device Type").click()
    page.get_by_role("button", name="Phone Device Type Select One").click()
    page.get_by_text("Mobile").click()
    page.get_by_role("group", name="Phone").click()
    page.get_by_role("button", name="Save and Continue").click()
    page.get_by_role("button", name="Error Phone Number").click()
    page.get_by_role("textbox", name="Phone Number").click()
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").fill("157 855 1545")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").fill("157855 1545")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").fill("1578551545")
    page.get_by_role("button", name="Save and Continue").click()
    page.get_by_role("button", name="Save and Continue").click()
    page.get_by_role("group", name="Work Experience 1", exact=True).get_by_label("Job Title*").dblclick()
    page.get_by_role("group", name="Work Experience 1", exact=True).get_by_label("Job Title*").click()
    page.get_by_role("group", name="Work Experience 1", exact=True).get_by_label("Job Title*").dblclick()
    page.get_by_role("group", name="Work Experience 1", exact=True).get_by_label("Location*").click()
    page.get_by_role("group", name="Work Experience 1", exact=True).get_by_label("Job Title*").fill("Principal Technical G& Presales")
    page.get_by_role("group", name="Work Experience 1", exact=True).get_by_label("Location*").fill("Germany")
    page.get_by_label("Work Experience 2", exact=True).get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 2", exact=True).get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 2", exact=True).get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 2", exact=True).get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 2", exact=True).get_by_role("button", name="Delete").click()
    page.get_by_role("group", name="Work Experience 4").get_by_label("Location*").click()
    page.get_by_role("group", name="Work Experience 4").get_by_label("Location*").fill("Germany")
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_label("Work Experience 6").get_by_role("button", name="Delete").click()
    page.get_by_role("group", name="Education 1").get_by_label("Degree Select One Required").click()
    page.get_by_text("Bachelors").click()
    page.get_by_role("group", name="Education 1").get_by_label("Overall Result (GPA)").click()
    page.get_by_role("group", name="Education 1").get_by_label("Overall Result (GPA)").fill("84")
    page.locator("div:nth-child(3) > div:nth-child(4) > .css-bh8c3f > .css-zfgw5f").click()
    page.get_by_role("button", name="Save and Continue").click()
    page.get_by_role("group", name="Are you eligible/legally").get_by_label("Select One Required").click()
    page.get_by_text("Yes").click()
    page.get_by_role("button", name="Select One", exact=True).click()
    page.get_by_text("No", exact=True).click()
    page.get_by_role("button", name="Select One Required").click()
    page.get_by_role("listbox").get_by_text("No").click()
    page.get_by_role("button", name="Save and Continue").click()
    page.get_by_role("checkbox", name="I consent to the Kyndryl").check()
    page.get_by_role("button", name="Save and Continue").click()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("button", name="Return to Home").click()
