import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://jobs.ashbyhq.com/n8n/353d6536-bce8-424d-b4d5-8f7f93258fe6/application?utm_source=kvb7ldmbNl")
    page.get_by_role("button", name="Upload file", exact=True).click()
    page.get_by_role("button", name="Choose File").set_input_files("Evgeny Vainshtein - CV 2026.pdf")
    page.get_by_role("checkbox", name="I can be based in Germany and").check()
    page.get_by_role("checkbox", name="I can be based in a European").check()
    page.get_by_role("checkbox", name="I want to be based in a").check()
    page.get_by_role("combobox", name="Start typing...").click()
    page.get_by_role("combobox", name="Start typing...").fill("Germany")
    page.get_by_role("option", name="Germany").click()
    page.get_by_role("textbox", name="What is your expected yearly").click()
    page.get_by_role("textbox", name="What is your expected yearly").fill("150000")
    page.get_by_role("textbox", name="Notice period / availability").click()
    page.get_by_role("textbox", name="Notice period / availability").fill("one month")
    page.get_by_role("textbox", name="What about n8n and the role").click()
    page.get_by_role("radio", name="I've been building workflows with n8n for over a year").check()
    page.get_by_role("radio", name="to 10 years").check()
    page.get_by_role("radio", name="I built or scaled a revenue/sales enablement function at a developer-tool, open").check()
    page.get_by_role("radio", name="I scaled a revenue/sales").check()
    page.get_by_role("radio", name="I selected and owned the").check()
    page.get_by_role("radio", name="I regularly coach sales reps").check()
    page.locator("#root").click()
    page.get_by_role("textbox", name="Tell us about one enterprise").fill("I had governed 70 sales reps 40 direct b2b and 30 that were responsible for channel at Colt Technology (6k company and 400 sales reps) I was responsible for strategic sales and building Cyber Security business group up in DACH including implementing new methodologies for sales growth around 100-300% in meetings and pipeline per sales rep per week")
    page.get_by_role("radio", name="I tie enablement programs to").check()
    page.get_by_role("radio", name="-49").check()
    page.get_by_role("radio", name="Man", exact=True).check()
    page.get_by_role("radio", name="No", exact=True).check()
    page.get_by_role("checkbox", name="Heterosexual / straight").check()
    page.get_by_role("checkbox", name="White").check()
    page.get_by_role("checkbox", name="None of the above").check()
    page.get_by_role("checkbox", name="I agree").check()
    page.get_by_role("button", name="Submit Application").click()
    page.get_by_role("button", name="What about n8n and the role").click()
    page.get_by_role("textbox", name="What about n8n and the role").click()
    page.get_by_role("textbox", name="What about n8n and the role").fill("I love the product and open source. I used to work in Redhat and Canonical.\nI'm also a builder and I develop tools to increase sales for sales reps. So I love anything that makes integration, orchestration easier")
    page.get_by_role("button", name="Submit Application").click()
