import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://jobs.ashbyhq.com/n8n/353d6536-bce8-424d-b4d5-8f7f93258fe6/application?utm_source=kvb7ldmbNl');
  await page.getByRole('button', { name: 'Upload file', exact: true }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('Evgeny Vainshtein - CV 2026.pdf');
  await page.getByRole('checkbox', { name: 'I can be based in Germany and' }).check();
  await page.getByRole('checkbox', { name: 'I can be based in a European' }).check();
  await page.getByRole('checkbox', { name: 'I want to be based in a' }).check();
  await page.getByRole('combobox', { name: 'Start typing...' }).click();
  await page.getByRole('combobox', { name: 'Start typing...' }).fill('Germany');
  await page.getByRole('option', { name: 'Germany' }).click();
  await page.getByRole('textbox', { name: 'What is your expected yearly' }).click();
  await page.getByRole('textbox', { name: 'What is your expected yearly' }).fill('150000');
  await page.getByRole('textbox', { name: 'Notice period / availability' }).click();
  await page.getByRole('textbox', { name: 'Notice period / availability' }).fill('one month');
  await page.getByRole('textbox', { name: 'What about n8n and the role' }).click();
  await page.getByRole('radio', { name: 'I\'ve been building workflows with n8n for over a year' }).check();
  await page.getByRole('radio', { name: 'to 10 years' }).check();
  await page.getByRole('radio', { name: 'I built or scaled a revenue/sales enablement function at a developer-tool, open' }).check();
  await page.getByRole('radio', { name: 'I scaled a revenue/sales' }).check();
  await page.getByRole('radio', { name: 'I selected and owned the' }).check();
  await page.getByRole('radio', { name: 'I regularly coach sales reps' }).check();
  await page.locator('#root').click();
  await page.getByRole('textbox', { name: 'Tell us about one enterprise' }).fill('I had governed 70 sales reps 40 direct b2b and 30 that were responsible for channel at Colt Technology (6k company and 400 sales reps) I was responsible for strategic sales and building Cyber Security business group up in DACH including implementing new methodologies for sales growth around 100-300% in meetings and pipeline per sales rep per week');
  await page.getByRole('radio', { name: 'I tie enablement programs to' }).check();
  await page.getByRole('radio', { name: '-49' }).check();
  await page.getByRole('radio', { name: 'Man', exact: true }).check();
  await page.getByRole('radio', { name: 'No', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Heterosexual / straight' }).check();
  await page.getByRole('checkbox', { name: 'White' }).check();
  await page.getByRole('checkbox', { name: 'None of the above' }).check();
  await page.getByRole('checkbox', { name: 'I agree' }).check();
  await page.getByRole('button', { name: 'Submit Application' }).click();
  await page.getByRole('button', { name: 'What about n8n and the role' }).click();
  await page.getByRole('textbox', { name: 'What about n8n and the role' }).click();
  await page.getByRole('textbox', { name: 'What about n8n and the role' }).fill('I love the product and open source. I used to work in Redhat and Canonical.\nI\'m also a builder and I develop tools to increase sales for sales reps. So I love anything that makes integration, orchestration easier');
  await page.getByRole('button', { name: 'Submit Application' }).click();
});