import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://careers.meliorefoundation.org/postings/03ed778b-2aef-4914-83ad-38de78ac65f4")
    page.get_by_role("button", name="Accept all").click()
    page.locator("#external-jobs-show-meta-desktop").get_by_role("link", name="Apply Now").click()
    page.locator("#application-form-page").click()
    page.locator("body").press("ArrowDown")
    page.locator("body").press("ArrowDown")
    page.locator("body").press("ArrowDown")
    page.locator("body").press("ArrowDown")
    page.locator("body").press("ArrowDown")
    page.get_by_role("textbox", name="First Name*").click()
    page.get_by_role("textbox", name="First Name*").fill("Evgeny")
    page.get_by_role("textbox", name="First Name*").press("Tab")
    page.get_by_role("textbox", name="Last Name*").fill("Vainshtein")
    page.get_by_role("textbox", name="Last Name*").press("Tab")
    page.get_by_role("textbox", name="Email Address*").fill("evgeny@s4biz.io")
    page.get_by_role("textbox", name="Email Address*").press("Tab")
    page.get_by_title("Belgium (België): +").click()
    page.get_by_title("Belgium (België): +").press("ArrowDown")
    page.get_by_text("Germany (Deutschland)+").click()
    page.get_by_role("textbox", name="Phone*").click()
    page.get_by_role("textbox", name="Phone*").fill("15785541545")
    page.get_by_role("textbox", name="LinkedIn URL").click()
    page.get_by_role("textbox", name="LinkedIn URL").fill("https://careers.meliorefoundation.org/postings/03ed778b-2aef-4914-83ad-38de78ac65f4")
    page.get_by_role("textbox", name="LinkedIn URL").press("ControlOrMeta+z")
    page.get_by_role("textbox", name="LinkedIn URL").fill("https://www.linkedin.com/in/feranicus/")
    page.get_by_role("textbox", name="LinkedIn URL").click()
    page.locator(".react-select__input-container").first.click()
    page.get_by_role("group", name="1.Personal Details We'll need").get_by_role("combobox").fill("ger")
    page.locator("#react-select-2-option-115").click()
    page.get_by_role("textbox", name="Address Line 1").click()
    page.get_by_role("textbox", name="Address Line 1").fill("Herman Bach J Weg 16")
    page.get_by_role("textbox", name="Town").click()
    page.get_by_role("textbox", name="Town").fill("Friedberg")
    page.get_by_role("textbox", name="Town").press("Tab")
    page.get_by_role("textbox", name="Postcode").fill("61169")
    page.get_by_text("Attach Résumé / CV").click()
    page.get_by_text("Attach Résumé / CV").set_input_files("Evgeny Vainshtein - CV 2026.pdf")
    page.locator("#react-select-3-placeholder").click()
    page.get_by_text("Yes without any administrative constraint", exact=True).click()
    page.locator("div").filter(has_text="1.Personal Details We'll need").nth(2).click()
    page.get_by_text("Attach", exact=True).click()
    page.get_by_text("Attach", exact=True).set_input_files("Evgeny Vainshtein - Cover Letter 2026.pdf")
    page.get_by_text("No", exact=True).click()
    page.get_by_role("textbox", name="Describe a specific instance").click()
    page.get_by_role("textbox", name="Describe a specific instance").fill("I had build www.cybergod.ai from scratch myself because there was a clear pain point in Sales department of Colt Technology Services (Company of 6k employees with 400 Sales reps). My AI platform increased meeting creation for Cyber Security Sales by 300% per week per sales rep.\nThe platform completely removes the discovery stage and gives each Sales person on a golden plate all cyber security issues of any company in the world")
    page.get_by_role("textbox", name="In this role, you’ll").click()
    page.get_by_role("textbox", name="In this role, you’ll").fill("I think what is important is actually not the tech but \"What customer wants\". What are his business objectives, his pain points, his business KPI's, What keeps him up at night. If this is unknown or the customer doesn't want to give out this informaiton.\nWe need to dig deeper and find out ourselfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer")
    page.get_by_role("textbox", name="In this role, you’ll").click()
    page.get_by_role("textbox", name="In this role, you’ll").click(button="right")
    page.get_by_role("textbox", name="In this role, you’ll").click()
    page.get_by_role("textbox", name="In this role, you’ll").fill("I think what is important is actually not the tech but \"What customer wants\". What are his business objectives, his pain points, his business KPI's, What keeps him up at night. If this is unknown or th e customer doesn't want to give out this informaiton.\nWe need to dig deeper and find out ourselfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer")
    page.get_by_role("textbox", name="In this role, you’ll").click()
    page.get_by_role("textbox", name="In this role, you’ll").fill("I think what is important is actually not the tech but \"What customer wants\". What are his business objectives, his pain points, his business KPI's, What keeps him up at night. If this is unknown or th e customer doesn't want to give out this informaiton.\nWe need to dig deeper and find out ourselfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").fill("I think what is important is actually not the tech but \"What customer wants\". What are his business objectives, his pain points, his business KPI's, What keeps him up at night. If this is unknown or the customer doesn't want to give out this informaiton.\nWe need to dig deeper and find out ourselfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer")
    page.get_by_role("textbox", name="In this role, you’ll").click()
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowDown")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").fill("I think what is important is actually not the tech but \"What customer wants\". What are his business objectives, his pain points, his business KPI's, What keeps him up at night. If this is unknown or the customer doesn't want to give out this informaiton.\nWe need to dig deeper and find out our selfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowUp")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowUp")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowDown")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowRight")
    page.get_by_role("textbox", name="In this role, you’ll").fill("I think what is important is actually not the tech but \"What customer wants\". What are his business objectives, his pain points, his business KPI's, What keeps him up at night. If this is unknown or the customer doesn't want to give out this information.\nWe need to dig deeper and find out our selfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowDown")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").press("ArrowLeft")
    page.get_by_role("textbox", name="In this role, you’ll").fill("I think what is important is actually not the tech but \"What customer wants\". What are his business objectives, his pain points, his business KPI's, What keeps him up at night. If this is unknown or the customer doesn't want to give out this information.\nWe need to dig deeper and find out our self and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer")
    page.get_by_role("checkbox", name="Allow us to process your").check()
    page.get_by_role("button", name="Submit Application").click()
