import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://careers.meliorefoundation.org/postings/03ed778b-2aef-4914-83ad-38de78ac65f4');
  await page.getByRole('button', { name: 'Accept all' }).click();
  await page.locator('#external-jobs-show-meta-desktop').getByRole('link', { name: 'Apply Now' }).click();
  await page.locator('#application-form-page').click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('Evgeny');
  await page.getByRole('textbox', { name: 'First Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('Vainshtein');
  await page.getByRole('textbox', { name: 'Last Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email Address*' }).fill('evgeny@s4biz.io');
  await page.getByRole('textbox', { name: 'Email Address*' }).press('Tab');
  await page.getByTitle('Belgium (België): +').click();
  await page.getByTitle('Belgium (België): +').press('ArrowDown');
  await page.getByText('Germany (Deutschland)+').click();
  await page.getByRole('textbox', { name: 'Phone*' }).click();
  await page.getByRole('textbox', { name: 'Phone*' }).fill('15785541545');
  await page.getByRole('textbox', { name: 'LinkedIn URL' }).click();
  await page.getByRole('textbox', { name: 'LinkedIn URL' }).fill('https://careers.meliorefoundation.org/postings/03ed778b-2aef-4914-83ad-38de78ac65f4');
  await page.getByRole('textbox', { name: 'LinkedIn URL' }).press('ControlOrMeta+z');
  await page.getByRole('textbox', { name: 'LinkedIn URL' }).fill('https://www.linkedin.com/in/feranicus/');
  await page.getByRole('textbox', { name: 'LinkedIn URL' }).click();
  await page.locator('.react-select__input-container').first().click();
  await page.getByRole('group', { name: '1.Personal Details We\'ll need' }).getByRole('combobox').fill('ger');
  await page.locator('#react-select-2-option-115').click();
  await page.getByRole('textbox', { name: 'Address Line 1' }).click();
  await page.getByRole('textbox', { name: 'Address Line 1' }).fill('Herman Bach J Weg 16');
  await page.getByRole('textbox', { name: 'Town' }).click();
  await page.getByRole('textbox', { name: 'Town' }).fill('Friedberg');
  await page.getByRole('textbox', { name: 'Town' }).press('Tab');
  await page.getByRole('textbox', { name: 'Postcode' }).fill('61169');
  await page.getByText('Attach Résumé / CV').click();
  await page.getByText('Attach Résumé / CV').setInputFiles('Evgeny Vainshtein - CV 2026.pdf');
  await page.locator('#react-select-3-placeholder').click();
  await page.getByText('Yes without any administrative constraint', { exact: true }).click();
  await page.locator('div').filter({ hasText: '1.Personal Details We\'ll need' }).nth(2).click();
  await page.getByText('Attach', { exact: true }).click();
  await page.getByText('Attach', { exact: true }).setInputFiles('Evgeny Vainshtein - Cover Letter 2026.pdf');
  await page.getByText('No', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Describe a specific instance' }).click();
  await page.getByRole('textbox', { name: 'Describe a specific instance' }).fill('I had build www.cybergod.ai from scratch myself because there was a clear pain point in Sales department of Colt Technology Services (Company of 6k employees with 400 Sales reps). My AI platform increased meeting creation for Cyber Security Sales by 300% per week per sales rep.\nThe platform completely removes the discovery stage and gives each Sales person on a golden plate all cyber security issues of any company in the world');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).click();
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).fill('I think what is important is actually not the tech but "What customer wants". What are his business objectives, his pain points, his business KPI\'s, What keeps him up at night. If this is unknown or the customer doesn\'t want to give out this informaiton.\nWe need to dig deeper and find out ourselfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).click();
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).click({
    button: 'right'
  });
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).click();
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).fill('I think what is important is actually not the tech but "What customer wants". What are his business objectives, his pain points, his business KPI\'s, What keeps him up at night. If this is unknown or th e customer doesn\'t want to give out this informaiton.\nWe need to dig deeper and find out ourselfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).click();
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).fill('I think what is important is actually not the tech but "What customer wants". What are his business objectives, his pain points, his business KPI\'s, What keeps him up at night. If this is unknown or th e customer doesn\'t want to give out this informaiton.\nWe need to dig deeper and find out ourselfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).fill('I think what is important is actually not the tech but "What customer wants". What are his business objectives, his pain points, his business KPI\'s, What keeps him up at night. If this is unknown or the customer doesn\'t want to give out this informaiton.\nWe need to dig deeper and find out ourselfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).click();
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).fill('I think what is important is actually not the tech but "What customer wants". What are his business objectives, his pain points, his business KPI\'s, What keeps him up at night. If this is unknown or the customer doesn\'t want to give out this informaiton.\nWe need to dig deeper and find out our selfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).fill('I think what is important is actually not the tech but "What customer wants". What are his business objectives, his pain points, his business KPI\'s, What keeps him up at night. If this is unknown or the customer doesn\'t want to give out this information.\nWe need to dig deeper and find out our selfs and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'In this role, you’ll' }).fill('I think what is important is actually not the tech but "What customer wants". What are his business objectives, his pain points, his business KPI\'s, What keeps him up at night. If this is unknown or the customer doesn\'t want to give out this information.\nWe need to dig deeper and find out our self and create a technology solution to make customer life easy.\nThat what a good Amazon AWS School tought me to work always backwards from the customer');
  await page.getByRole('checkbox', { name: 'Allow us to process your' }).check();
  await page.getByRole('button', { name: 'Submit Application' }).click();
});