import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://job-boards.greenhouse.io/okx/jobs/7699600003?gh_src=8ad01c4c3us")
    page.get_by_role("button", name="Apply").click()
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("textbox", name="First Name").fill("Evgeny")
    page.get_by_role("textbox", name="First Name").press("Tab")
    page.get_by_role("textbox", name="Last Name").fill("Vainshtein")
    page.get_by_role("textbox", name="Last Name").press("Tab")
    page.get_by_role("textbox", name="Email").fill("evgeny@s4biz.io")
    page.locator(".select__control").first.click()
    page.get_by_role("option", name="Germany +").click()
    page.get_by_role("textbox", name="Phone").fill("15785541545")
    page.locator(".field-wrapper > .select > .select__container > .select-shell > div > .select__control > .select__value-container > .select__input-container").first.click()
    page.get_by_role("combobox", name="Location (City)").fill("Friedberg")
    page.get_by_role("option", name="Friedberg, Hesse, Germany").click()
    page.get_by_label("Resume/CV*").locator("button").filter(has_text="Attach").click()
    page.get_by_role("group", name="Resume/CV*").get_by_label("Attach").set_input_files("Evgeny Vainshtein - CV 2026.pdf")
    page.locator("button").filter(has_text="Attach").click()
    page.get_by_label("Attach").set_input_files("Evgeny Vainshtein - Cover Letter 2026.pdf")
    page.get_by_role("textbox", name="LinkedIn Profile").click()
    page.get_by_role("textbox", name="LinkedIn Profile").fill("https://www.linkedin.com/in/feranicus/")
    page.get_by_role("textbox", name="LinkedIn Profile").click()
    page.get_by_text("How did you hear about us?*").click()
    page.locator(".select__control.select__control--is-focused > .select__value-container > .select__input-container").click()
    page.get_by_role("option", name="LinkedIn").click()
    page.locator(".eeoc__question__wrapper > .select > .select__container > .select-shell > div > .select__control > .select__value-container > .select__input-container").first.click()
    page.get_by_role("option", name="Male", exact=True).click()
    page.locator("div:nth-child(4) > .select > .select__container > .select-shell > div > .select__control > .select__value-container > .select__input-container").click()
    page.get_by_role("option", name="No").click()
    page.locator("div:nth-child(6) > .select > .select__container > .select-shell > div > .select__control > .select__value-container > .select__input-container").click()
    page.get_by_role("option", name="I am not a protected veteran").click()
    page.locator("div:nth-child(9) > .select > .select__container > .select-shell > div > .select__control > .select__value-container > .select__input-container").click()
    page.get_by_role("option", name="No, I do not have a").click()
    page.get_by_role("button", name="Submit application").click()
