import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://job-boards.greenhouse.io/tanium/jobs/7800463?gh_src=f0ee6cde1us")
    page.get_by_role("button", name="Apply").click()
    page.get_by_role("textbox", name="First Name", exact=True).fill("Evgeny")
    page.get_by_role("textbox", name="First Name", exact=True).press("Tab")
    page.get_by_role("textbox", name="Last Name").fill("Vainsteins")
    page.get_by_role("textbox", name="Last Name").press("Tab")
    page.get_by_role("textbox", name="Preferred First Name").fill("Jev")
    page.get_by_role("textbox", name="Preferred First Name").press("Tab")
    page.get_by_role("textbox", name="Email").fill("evgeny@s4biz.io")
    page.get_by_role("textbox", name="Email").press("Tab")
    page.get_by_role("combobox", name="Country").fill("ger")
    page.get_by_role("option", name="Germany +").click()
    page.get_by_role("textbox", name="Phone").fill("15785541545")
    page.locator(".field-wrapper > .select > .select__container > .select-shell > div > .select__control--outside-label > .select__value-container > .select__input-container").first.click()
    page.get_by_role("combobox", name="Location (City)").fill("Friedberg 61169")
    page.locator(".select__input-container.remix-css-1cfo1cf").click()
    page.get_by_role("combobox", name="Location (City)").fill("Friedberg")
    page.get_by_role("option", name="Friedberg, Hesse, Germany").click()
    page.get_by_label("Resume/CV*").locator("button").filter(has_text="Attach").click()
    page.get_by_role("group", name="Resume/CV*").get_by_label("Attach").set_input_files("Evgeny Vainshtein - CV 2026.pdf")
    page.locator("body").click()
    page.get_by_role("textbox", name="Phone").press("ArrowDown")
    page.get_by_role("textbox", name="Phone").press("ArrowDown")
    page.get_by_role("textbox", name="Phone").press("ArrowDown")
    page.get_by_role("textbox", name="Phone").press("ArrowDown")
    page.get_by_role("textbox", name="Phone").press("ArrowDown")
    page.locator("button").filter(has_text="Attach").click()
    page.get_by_label("Attach").set_input_files("Evgeny Vainshtein - Cover Letter 2026.pdf")
    page.get_by_role("textbox", name="Website").click()
    page.get_by_role("textbox", name="Website").fill("itzen.ai")
    page.get_by_role("textbox", name="Website").press("Tab")
    page.get_by_role("textbox", name="LinkedIn Profile").fill("https://www.linkedin.com/in/feranicus/")
    page.get_by_role("textbox", name="LinkedIn Profile").click()
    page.get_by_role("textbox", name="How did you hear about Tanium?").click()
    page.get_by_role("textbox", name="How did you hear about Tanium?").fill("Linkedin")
    page.locator("div").filter(has_text=re.compile(r"^Select\.\.\.$")).nth(2).click()
    page.get_by_role("option", name="LinkedIn").click()
    page.get_by_role("textbox", name="If you selected Employee").click()
    page.get_by_role("textbox", name="If you selected Employee").fill("N/A")
    page.locator("div:nth-child(7) > .select > .select__container > .select-shell > div > .select__control--outside-label > .select__value-container > .select__input-container").click()
    page.get_by_role("option", name="No").click()
    page.locator("div:nth-child(8) > .select > .select__container > .select-shell > div > .select__control--outside-label > .select__value-container > .select__input-container").click()
    page.get_by_role("option", name="Continue").click()
    page.get_by_role("button", name="Submit application").click()
