import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://job-boards.greenhouse.io/tanium/jobs/7800463?gh_src=f0ee6cde1us');
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('textbox', { name: 'First Name', exact: true }).fill('Evgeny');
  await page.getByRole('textbox', { name: 'First Name', exact: true }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Vainsteins');
  await page.getByRole('textbox', { name: 'Last Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Preferred First Name' }).fill('Jev');
  await page.getByRole('textbox', { name: 'Preferred First Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).fill('evgeny@s4biz.io');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('combobox', { name: 'Country' }).fill('ger');
  await page.getByRole('option', { name: 'Germany +' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('15785541545');
  await page.locator('.field-wrapper > .select > .select__container > .select-shell > div > .select__control--outside-label > .select__value-container > .select__input-container').first().click();
  await page.getByRole('combobox', { name: 'Location (City)' }).fill('Friedberg 61169');
  await page.locator('.select__input-container.remix-css-1cfo1cf').click();
  await page.getByRole('combobox', { name: 'Location (City)' }).fill('Friedberg');
  await page.getByRole('option', { name: 'Friedberg, Hesse, Germany' }).click();
  await page.getByLabel('Resume/CV*').locator('button').filter({ hasText: 'Attach' }).click();
  await page.getByRole('group', { name: 'Resume/CV*' }).getByLabel('Attach').setInputFiles('Evgeny Vainshtein - CV 2026.pdf');
  await page.locator('body').click();
  await page.getByRole('textbox', { name: 'Phone' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Phone' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Phone' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Phone' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Phone' }).press('ArrowDown');
  await page.locator('button').filter({ hasText: 'Attach' }).click();
  await page.getByLabel('Attach').setInputFiles('Evgeny Vainshtein - Cover Letter 2026.pdf');
  await page.getByRole('textbox', { name: 'Website' }).click();
  await page.getByRole('textbox', { name: 'Website' }).fill('itzen.ai');
  await page.getByRole('textbox', { name: 'Website' }).press('Tab');
  await page.getByRole('textbox', { name: 'LinkedIn Profile' }).fill('https://www.linkedin.com/in/feranicus/');
  await page.getByRole('textbox', { name: 'LinkedIn Profile' }).click();
  await page.getByRole('textbox', { name: 'How did you hear about Tanium?' }).click();
  await page.getByRole('textbox', { name: 'How did you hear about Tanium?' }).fill('Linkedin');
  await page.locator('div').filter({ hasText: /^Select\.\.\.$/ }).nth(2).click();
  await page.getByRole('option', { name: 'LinkedIn' }).click();
  await page.getByRole('textbox', { name: 'If you selected Employee' }).click();
  await page.getByRole('textbox', { name: 'If you selected Employee' }).fill('N/A');
  await page.locator('div:nth-child(7) > .select > .select__container > .select-shell > div > .select__control--outside-label > .select__value-container > .select__input-container').click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.locator('div:nth-child(8) > .select > .select__container > .select-shell > div > .select__control--outside-label > .select__value-container > .select__input-container').click();
  await page.getByRole('option', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Submit application' }).click();
});