import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://intive.wd3.myworkdayjobs.com/Intive/job/Remote-Germany/Chief-Commercial-Officer---General-Manager---EMEA_JR101912?source=LinkedIn")
    page.get_by_role("button", name="Apply").click()
    page.get_by_role("button", name="Autofill with Resume").click()
    page.get_by_role("button", name="Accept Cookies").click()
    page.get_by_role("button", name="Select file").click()
    page.locator("input[type=\"file\"]").set_input_files("Evgeny Vainshtein - CV 2026.pdf")
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="How Did You Hear About Us?").click()
    page.get_by_text("LinkedIn corporate page").click()
    page.get_by_role("radio", name="No").check()
    page.get_by_role("button", name="Country Georgia Required").click()
    page.get_by_text("Germany").click()
    page.get_by_role("textbox", name="Street").click()
    page.get_by_role("textbox", name="Street").fill("Herman J Bach Weg 16")
    page.get_by_role("textbox", name="Postal Code").click()
    page.get_by_role("textbox", name="Postal Code").fill("61169")
    page.get_by_role("textbox", name="City").dblclick()
    page.get_by_role("textbox", name="City").fill("Friedberg")
    page.get_by_role("textbox", name="Phone Number").click()
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").fill("+49 157 8551545")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").fill("+49 1578551545")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").press("ArrowLeft")
    page.get_by_role("textbox", name="Phone Number").fill("1578551545")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").press("ArrowRight")
    page.get_by_role("textbox", name="Phone Number").fill("15785541545")
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Calendar").click()
    page.get_by_role("button", name="Next month").click()
    page.get_by_role("button", name="Thursday 17 September").click()
    page.locator("#primaryQuestionnaire--e55467596803100100f34ed769170000").click()
    page.locator("#primaryQuestionnaire--e55467596803100100f34ed769170000").fill("130k base + 70k bonus + Car")
    page.get_by_role("button", name="Select One", exact=True).click()
    page.get_by_role("option", name="Yes").click()
    page.get_by_role("button", name="Select One Required").click()
    page.get_by_role("listbox").get_by_text("Yes").click()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("checkbox", name="I acknowledge and want to").check()
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("button", name="Close").click()
